language: go
go:
- 1.8.3
before_deploy:
- ./build.sh
deploy:
  provider: releases
  api_key:
    secure: m9BP3idjWultjjdHYHNMfRhnNDkia9MkbvnBkXvSemfoCQzInMUObAt3MtRCrs1sUtlgqYWDuq7MaB20YnsGHBj3C3Esgw1aw+Ak1HOSx1X6lennASvRInBVyEfTL7JKgeJQ0F2xHqbocOa6ExRo30CCnNLRpo9KoySRuVvyWqFDTRKU6lwpN6PskW37+U8i9qNzM9LOeJUH3NogmCCgFIU8Qy1MYNn6vZ1y+NRn7WgO+wyTlcOnnXG/zDePu72EwVvKU6h/QMcoPZ9Kvm6RQ1DjAIyyLnO9ckzhVNYYz7HocIs16oB1zgSuX4OtLpioDLOsExw/SoCJ6FQcF9EdAnaDP4Ka6vVatzCqbIAQWcb0HDUEwW48bDK21eMmdmfI7emhjS0JaRBmeqpqItdk0WbPhWXDcibuNj0uyIRxQjpMMVrEIVWHNMtnYp6rrbvM/G+OJ9I2iAUMQx8DpRmPGMTnf55l7DWtPD355uOFlTOdHXFagflazUlhtROkrU1VOLgwiS9m0pQ9EyMYU0KOWrz5RbkFxeJ2pJS9VVKicLsLy/5xDST4IqW5zWun/9hzHohXaECgfeBoUB89t1W0BlU/ubapprPBaN6JZ16B9COC2dc+zuWL4w0gcUbyKLQbO4Lf80zJV5P0F3VkMOAig6B15xs94g/Mwlv74QTtT0E=
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/bin/*.tar.gz"
  on:
    tags: true
    all_branches: true
